// src/jiraConfig.js

const JIRA_CONFIG = {
    JIRA_URL: 'chewyinc.atlassian.net',
    JIRA_EMAIL: 'cmartin8@chewy.com',
    JIRA_API_KEY: 'ATATT3xFfGF0hRCi66Jvwda8W3FZRNbqpiW6gBuCktvXk4izwBSIAyLizzKTovplY2XqQG1oU8604SF6Ck0EXrDCNEVj6H8HxGhNEXawCNWL3zH2dy_BSM2sMz0rm2BDukgJySM0fRIC3WRxLXXbAfuayAhuAksMOK-OCf5aapYwvygwDS6NbUA=D0FE99FE',
    JIRA_AEXI_BOARD_ID: 1429,
    JIRA_AEXI_PROJECT_KEY: 'AEXI',
    JIRA_OCS_BOARD_ID: 405,
    JIRA_OCS_PROJECT_KEY: 'OCS',
    JIRA_AEXO_BOARD_ID: 3362,
    JIRA_AEXO_PROJECT_KEY: 'AEXO',
    JIRA_SAL_BOARD_ID: 1424,
    JIRA_SAL_PROJECT_KEY: 'SAL',
};

export default JIRA_CONFIG;